/** Number spans inserted by the export (design.md §7.1); never part of the document text. */
const RESOLVED_LABEL_SELECTOR = 'span.heading-number, span.caption-number';

/** Parts the export generates from meta / revisions / theme settings (design.md §6). */
const GENERATED_SECTION_SELECTOR =
  'section.doc-cover, section.doc-revisions, header.doc-header, footer.doc-footer';

function moveChildren(from: Element, to: Element): Element {
  to.append(...from.childNodes);
  return to;
}

function tableCaption(document: Document, source: Element): Element {
  const caption = document.createElement('div');
  caption.className = 'table-caption';
  return moveChildren(source, caption);
}

/** Wraps `table` (in place) as `div.table-figure > caption + table`. */
function wrapAsTableFigure(document: Document, caption: Element, table: Element): void {
  const wrapper = document.createElement('div');
  wrapper.className = 'table-figure';
  table.before(wrapper);
  wrapper.append(caption, table);
}

/**
 * Prepares external / pasted HTML for parsing (design.md §6):
 * - removes numbers inserted by the export, so they do not become text;
 * - removes the header, footer, cover and revision history generated by the export;
 * - rewrites table captions into `div.table-figure > div.table-caption + table`,
 *   because one element cannot be parsed into two nodes (tableFigure and table).
 */
export function normalizeImportedHtml(html: string): string {
  const document = new DOMParser().parseFromString(`<body>${html}</body>`, 'text/html');
  const { body } = document;

  for (const label of body.querySelectorAll(RESOLVED_LABEL_SELECTOR)) {
    label.remove();
  }
  for (const section of body.querySelectorAll(GENERATED_SECTION_SELECTOR)) {
    section.remove();
  }

  // <figure><table>…</table><figcaption>…</figcaption></figure>
  for (const figure of body.querySelectorAll('figure')) {
    const table = figure.querySelector(':scope > table');
    if (!table) continue;
    const figcaption = figure.querySelector(':scope > figcaption');
    const caption = tableCaption(document, figcaption ?? document.createElement('div'));
    figure.before(table);
    wrapAsTableFigure(document, caption, table);
    figure.remove();
  }

  // <table><caption>…</caption>…</table> (not already inside a table figure)
  for (const caption of body.querySelectorAll('table > caption')) {
    const table = caption.parentElement;
    caption.remove();
    if (table && !table.parentElement?.classList.contains('table-figure')) {
      wrapAsTableFigure(document, tableCaption(document, caption), table);
    }
  }

  return body.innerHTML;
}
